// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PreSpend.Api.Infrastructure.Persistence;

#nullable disable

namespace PreSpend.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260510114028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<DateOnly?>("ActualDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmotionalContext")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("emotional_context");

                    b.Property<decimal?>("PlannedBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("planned_budget");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("UserId", "PlannedDate")
                        .HasDatabaseName("ix_activities_user_id_planned_date");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.CashflowEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entry_type");

                    b.Property<string>("ExpenseType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expense_type");

                    b.Property<string>("IncomeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("income_type");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("SourceOrPayee")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_or_payee");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cashflow_entries");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_cashflow_entries_activity_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_cashflow_entries_category_id");

                    b.HasIndex("UserId", "EntryDate")
                        .HasDatabaseName("ix_cashflow_entries_user_id_entry_date");

                    b.ToTable("cashflow_entries", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_user_id_name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111001"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "groceries",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111002"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "bills",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111003"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "transport",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111004"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "food-drink",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111005"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "household",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111006"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "health",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111007"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "personal-care",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111008"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "shopping",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111009"),
                            CategoryType = "Expense",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "social",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111010"),
                            CategoryType = "Income",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "income",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111011"),
                            CategoryType = "Mixed",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            Name = "other",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.InsightRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_code");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_insight_rules");

                    b.HasIndex("RuleCode")
                        .IsUnique()
                        .HasDatabaseName("ix_insight_rules_rule_code");

                    b.ToTable("insight_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222001"),
                            Description = "Highlights activities where actual spend stayed below the planned budget.",
                            IsActive = true,
                            RuleCode = "planned_over_actual",
                            RuleName = "Planned under actual spend",
                            Severity = "Positive"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222002"),
                            Description = "Highlights activities where actual spend exceeded the planned budget.",
                            IsActive = true,
                            RuleCode = "actual_over_planned",
                            RuleName = "Actual over planned spend",
                            Severity = "Warning"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222003"),
                            Description = "Highlights actual line items that were not part of the spending plan.",
                            IsActive = true,
                            RuleCode = "unplanned_purchase_detected",
                            RuleName = "Unplanned purchase detected",
                            Severity = "Warning"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222004"),
                            Description = "Highlights completed activities where want-classified items outweighed need-classified items.",
                            IsActive = true,
                            RuleCode = "want_heavy_activity",
                            RuleName = "Want-heavy activity",
                            Severity = "Info"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222005"),
                            Description = "Highlights need-classified planned items that were not purchased during the activity.",
                            IsActive = true,
                            RuleCode = "neglected_essential",
                            RuleName = "Neglected essential",
                            Severity = "Info"
                        });
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.LineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CashflowEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashflow_entry_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("line_type");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SpendingPlanItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("spending_plan_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasPlanned")
                        .HasColumnType("boolean")
                        .HasColumnName("was_planned");

                    b.HasKey("Id")
                        .HasName("pk_line_items");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_line_items_activity_id");

                    b.HasIndex("CashflowEntryId")
                        .HasDatabaseName("ix_line_items_cashflow_entry_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_line_items_category_id");

                    b.HasIndex("SpendingPlanItemId")
                        .HasDatabaseName("ix_line_items_spending_plan_item_id");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_line_items_user_id_occurred_at");

                    b.ToTable("line_items", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message_template");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("TriggerCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_code");

                    b.HasKey("Id")
                        .HasName("pk_prompt_templates");

                    b.HasIndex("TriggerCode")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_templates_trigger_code");

                    b.ToTable("prompt_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MessageTemplate = "Planning {activityType} today?",
                            PromptType = "PlanActivity",
                            Severity = "Info",
                            TriggerCode = "plan_activity"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MessageTemplate = "Reuse your last {activityType} plan?",
                            PromptType = "ReuseTemplate",
                            Severity = "Info",
                            TriggerCode = "reuse_template"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MessageTemplate = "How did this activity compare with your plan?",
                            PromptType = "ReflectAfterActivity",
                            Severity = "Info",
                            TriggerCode = "reflect_after_activity"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MessageTemplate = "You spent more than planned last time. Want to plan this one?",
                            PromptType = "PlanAfterOverspend",
                            Severity = "Warning",
                            TriggerCode = "plan_after_overspend"
                        });
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedFromTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_from_template_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_spending_plans");

                    b.HasIndex("ActivityId")
                        .IsUnique()
                        .HasDatabaseName("ix_spending_plans_activity_id");

                    b.HasIndex("CreatedFromTemplateId")
                        .HasDatabaseName("ix_spending_plans_created_from_template_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_spending_plans_user_id");

                    b.ToTable("spending_plans", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<decimal>("PlannedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("planned_amount");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<Guid>("SpendingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("spending_plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_spending_plan_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_spending_plan_items_category_id");

                    b.HasIndex("SpendingPlanId")
                        .HasDatabaseName("ix_spending_plan_items_spending_plan_id");

                    b.ToTable("spending_plan_items", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_spending_plan_templates");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_spending_plan_templates_user_id");

                    b.ToTable("spending_plan_templates", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_amount");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_spending_plan_template_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_spending_plan_template_items_category_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_spending_plan_template_items_template_id");

                    b.ToTable("spending_plan_template_items", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("FamilySupportFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("family_support_flag");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("IncomeLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("income_level");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserAuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("provider_email");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_auth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_auth_identities_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_identities_provider_provider_user_id");

                    b.ToTable("user_auth_identities", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserBehaviorMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivitiesCompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("activities_completed_count");

                    b.Property<decimal>("ActualSpendingTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_spending_total");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ImpulsePurchaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("impulse_purchase_count");

                    b.Property<decimal>("ImpulsePurchaseTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("impulse_purchase_total");

                    b.Property<int>("NeglectedEssentialCount")
                        .HasColumnType("integer")
                        .HasColumnName("neglected_essential_count");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("period_type");

                    b.Property<decimal>("PlannedSpendingTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("planned_spending_total");

                    b.Property<int>("SpendingPlansCreatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("audits_created_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_behavior_metrics");

                    b.HasIndex("UserId", "PeriodType", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("ix_user_behavior_metrics_user_id_period_type_period_start_peri");

                    b.ToTable("user_behavior_metrics", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserFinancialProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IncomeFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("income_frequency");

                    b.Property<DateOnly?>("NextExpectedIncomeDate")
                        .HasColumnType("date")
                        .HasColumnName("next_expected_income_date");

                    b.Property<int?>("PaydayDayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("payday_day_of_month");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_financial_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_financial_profiles_user_id");

                    b.ToTable("user_financial_profiles", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InsightMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("insight_message");

                    b.Property<string>("InsightTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("insight_title");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_insights");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_user_insights_activity_id");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_user_insights_rule_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_insights_user_id");

                    b.ToTable("user_insights", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acted_at");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action_taken");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PromptTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_template_id");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_type");

                    b.Property<Guid>("RelatedActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_activity_id");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_prompts");

                    b.HasIndex("PromptTemplateId")
                        .HasDatabaseName("ix_user_prompts_prompt_template_id");

                    b.HasIndex("RelatedActivityId")
                        .HasDatabaseName("ix_user_prompts_related_activity_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_user_prompts_user_id_status");

                    b.ToTable("user_prompts", (string)null);
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.Activity", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.CashflowEntry", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.Activity", "Activity")
                        .WithMany("CashflowEntries")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cashflow_entries_activities_activity_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.Category", "Category")
                        .WithMany("CashflowEntries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cashflow_entries_categories_category_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("CashflowEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cashflow_entries_users_user_id");

                    b.Navigation("Activity");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.Category", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.LineItem", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.Activity", "Activity")
                        .WithMany("LineItems")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_line_items_activities_activity_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.CashflowEntry", "CashflowEntry")
                        .WithMany("LineItems")
                        .HasForeignKey("CashflowEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_line_items_cashflow_entries_cashflow_entry_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.Category", "Category")
                        .WithMany("LineItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_line_items_categories_category_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.SpendingPlanItem", "SpendingPlanItem")
                        .WithMany("LineItems")
                        .HasForeignKey("SpendingPlanItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_line_items_spending_plan_items_spending_plan_item_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("LineItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_line_items_users_user_id");

                    b.Navigation("Activity");

                    b.Navigation("CashflowEntry");

                    b.Navigation("Category");

                    b.Navigation("SpendingPlanItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlan", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.Activity", "Activity")
                        .WithOne("SpendingPlan")
                        .HasForeignKey("PreSpend.Api.Domain.Entities.SpendingPlan", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spending_plans_activities_activity_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.SpendingPlanTemplate", "CreatedFromTemplate")
                        .WithMany("CreatedSpendingPlans")
                        .HasForeignKey("CreatedFromTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_spending_plans_spending_plan_templates_created_from_templat");

                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("SpendingPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spending_plans_users_user_id");

                    b.Navigation("Activity");

                    b.Navigation("CreatedFromTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanItem", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.Category", "Category")
                        .WithMany("SpendingPlanItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_spending_plan_items_categories_category_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.SpendingPlan", "SpendingPlan")
                        .WithMany("Items")
                        .HasForeignKey("SpendingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spending_plan_items_spending_plans_spending_plan_id");

                    b.Navigation("Category");

                    b.Navigation("SpendingPlan");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanTemplate", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("SpendingPlanTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spending_plan_templates_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanTemplateItem", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.Category", "Category")
                        .WithMany("SpendingPlanTemplateItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_spending_plan_template_items_categories_category_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.SpendingPlanTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spending_plan_template_items_spending_plan_templates_templa");

                    b.Navigation("Category");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserAuthIdentity", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_auth_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserBehaviorMetric", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("BehaviorMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_behavior_metrics_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserFinancialProfile", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithOne("FinancialProfile")
                        .HasForeignKey("PreSpend.Api.Domain.Entities.UserFinancialProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_financial_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserInsight", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.Activity", "Activity")
                        .WithMany("Insights")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_insights_activities_activity_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.InsightRule", "Rule")
                        .WithMany("UserInsights")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_insights_insight_rules_rule_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("Insights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_insights_users_user_id");

                    b.Navigation("Activity");

                    b.Navigation("Rule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.UserPrompt", b =>
                {
                    b.HasOne("PreSpend.Api.Domain.Entities.PromptTemplate", "PromptTemplate")
                        .WithMany("UserPrompts")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_prompts_prompt_templates_prompt_template_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.Activity", "RelatedActivity")
                        .WithMany("Prompts")
                        .HasForeignKey("RelatedActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_prompts_activities_related_activity_id");

                    b.HasOne("PreSpend.Api.Domain.Entities.User", "User")
                        .WithMany("Prompts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_prompts_users_user_id");

                    b.Navigation("PromptTemplate");

                    b.Navigation("RelatedActivity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.Activity", b =>
                {
                    b.Navigation("CashflowEntries");

                    b.Navigation("Insights");

                    b.Navigation("LineItems");

                    b.Navigation("Prompts");

                    b.Navigation("SpendingPlan");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.CashflowEntry", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("CashflowEntries");

                    b.Navigation("LineItems");

                    b.Navigation("SpendingPlanItems");

                    b.Navigation("SpendingPlanTemplateItems");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.InsightRule", b =>
                {
                    b.Navigation("UserInsights");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.PromptTemplate", b =>
                {
                    b.Navigation("UserPrompts");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanItem", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.SpendingPlanTemplate", b =>
                {
                    b.Navigation("CreatedSpendingPlans");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("PreSpend.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AuthIdentities");

                    b.Navigation("BehaviorMetrics");

                    b.Navigation("CashflowEntries");

                    b.Navigation("Categories");

                    b.Navigation("FinancialProfile");

                    b.Navigation("Insights");

                    b.Navigation("LineItems");

                    b.Navigation("Prompts");

                    b.Navigation("SpendingPlanTemplates");

                    b.Navigation("SpendingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
